<a href="https://colab.research.google.com/github/SriKrishnaMishra/CICIDS2017-dataset-Project/blob/main/pytorch_fundamental_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

what is pytorch >

why use in ml >

how pytorch is working with ml >

what are the benifits and issue in pytorch >

how work with pytorch >

why pytorch is on demand >

there are the my basic pytorch quest >

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


question :

what is gpu or tpu or tensor

what is Tensir and Introdution to Tensor ⁉
create tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor (ndim)

TENSOR = torch.tensor([[[1,2,3], [2, 4, 5],[7, 8 , 9] ]])
TENSOR

tensor([[[1, 2, 3],
         [2, 4, 5],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0], TENSOR[0,1,1], TENSOR[0,2,2]

(tensor([[1, 2, 3],
         [2, 4, 5],
         [7, 8, 9]]),
 tensor(4),
 tensor(9))

###RANDOM TENSOR

In [ ]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.5491, 0.6531, 0.1760, 0.8011],
         [0.2508, 0.5574, 0.3758, 0.0818],
         [0.3939, 0.4792, 0.3376, 0.3868]]])

In [ ]:
# create a random tensor with similar shape to an image shape
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
#random data

torch.rand(3, 3)

tensor([[0.0322, 0.1246, 0.7558],
        [0.1147, 0.4888, 0.6887],
        [0.5727, 0.2950, 0.6394]])

# zero and ones

In [ ]:
# create a tensor of all zero
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

###creating a range of tensors and tensors-like


In [ ]:
# use torch.range()

one_to_ten =   torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [ ]:
#float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9 ], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting-infomation from tensors

1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right devices

In [ ]:
# create a tensor

some_tensor = torch.rand(3, 5)
some_tensor

tensor([[0.9967, 0.9235, 0.4191, 0.0919, 0.1848],
        [0.7264, 0.7574, 0.9679, 0.0157, 0.4603],
        [0.1735, 0.0275, 0.4952, 0.8211, 0.0227]])

In [ ]:
#find out details about some tensor

print(some_tensor)
print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor : {some_tensor.shape}")
print(f"device of tensor : {some_tensor.device}")

tensor([[0.9967, 0.9235, 0.4191, 0.0919, 0.1848],
        [0.7264, 0.7574, 0.9679, 0.0157, 0.4603],
        [0.1735, 0.0275, 0.4952, 0.8211, 0.0227]])
datatype of tensor : torch.float32
shape of tensor : torch.Size([3, 5])
device of tensor : cpu


In [ ]:
# create a tensor addition

tensor = torch.tensor([1, 2, 3])
tensor + 190

tensor([191, 192, 193])


# Manipulating Tensors (tensor operations)
Tensor opertions include:

Addition

Subtraction

Multiplication (element-wise)

Division

Matrix multiplication

In [ ]:
# create a tensor multiple

tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
tensor - 10


tensor([ 0, 10, 20])

In [ ]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

### matrix multiplication

Two main way of profomed this task like multiplication in neural networks and deep learning

element wise multiplication
matrix multiplication (dot product)

In [ ]:
#element wise

print(tensor, "*", tensor)
print(f"equals : {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
equals : tensor([100, 400, 900])


In [ ]:
# matrix multiplication

torch.matmul(tensor, tensor)

tensor(1400)

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
#time
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 463 µs, sys: 69 µs, total: 532 µs
Wall time: 575 µs


In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 40 µs, sys: 7 µs, total: 47 µs
Wall time: 50.1 µs


tensor(1400)

# Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:

Element-wise multiplication
Matrix mutliplication (dot product)

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [ ]:
#matrix mutiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 392 µs, sys: 59 µs, total: 451 µs
Wall time: 456 µs


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 26 µs, sys: 4 µs, total: 30 µs
Wall time: 32.9 µs


tensor(1400)


# One of the most common errors in deep learning: shape errors

In [ ]:
#shapes for matric multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B, tensor_B.shape



(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

find the min, max, mean, sum etc in tensor aggregation

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))


# Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin

<function Tensor.argmin>

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

# Reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:

x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

# Indexing (selecting data from tensors)

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:

# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]


tensor([1, 2, 3])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[:, 0]


tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]


tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]


tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
print(x[0][2][2])


tensor(9)


In [ ]:
print(x[:, :, 2])

tensor([[3, 6, 9]])


| Syntax              | Meaning                                  |
| ------------------- | ---------------------------------------- |
| `x[i]`              | Index i-th item along first dim          |
| `x[i, j]`           | Index i-th along dim 0, j-th along dim 1 |
| `x[:, i, :]`        | All batches, i-th row                    |
| `x[x > 5]`          | Boolean masking                          |
| `x[[0, 1], [1, 2]]` | Fancy indexing                           |


# PyTorch tensors & NumPy

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))